# Generated by Django 2.2.4 on 2019-08-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
